variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""
  
stages:
  - build
  - deploy

build_subproject1:
  stage: build
  image: docker:20.10
  services:
    - name: docker:20-dind
      alias: docker
      command: ["--tls=false"]
  before_script:
    -
  script:
    - cd subproject1
    - docker build -t .dkr.ecr.us-east-1.amazonaws.com/subproject1:${CI_COMMIT_SHA} .
    - docker push .dkr.ecr.us-east-1.amazonaws.com/subproject1:${CI_COMMIT_SHA}

deploy_subproject1:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    # Set the new image tag in the kustomization file
    - sed -i "s|<IMAGE_TAG>|${CI_COMMIT_SHA}|g" k8s/dev/app-deployment.yml
    # Apply the updated configuration
    - kubectl kustomize k8s/dev | kubectl apply -f -
  rules:
    - changes:
        - '**/*'
