FROM openjdk:14.0-jdk-buster as dev

WORKDIR /work

COPY mvnw /work/mvnw
COPY .mvn /work/.mvn
COPY pom.xml /work/pom.xml

RUN chmod +x /work/mvnw
RUN ./mvnw dependency:go-offline

COPY . /work/

# Add the chmod command again right before the mvnw install command.
RUN chmod +x /work/mvnw
RUN ./mvnw install

RUN chmod +x /work/target/demo-0.0.1-SNAPSHOT.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","/work/target/demo-0.0.1-SNAPSHOT.jar"]
