repositories:
- name: stable
  url: https://charts.helm.sh/stable

environments:
  development:
    values:
      - kustomize: kustomize/demo/overlays/development/kustomization.yaml
  production:
    values:
      - kustomize: kustomize/demo/overlays/production/kustomization.yaml

releases:
  - name: example-app
    chart: kustomize/demo
